language: python
python:
  - 3.6
  - 3.7
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

sudo: false

addons:
  apt:
    packages:
      # Some tests do a pdf conversion, so install latex which is needed for that.
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - lmodern
install:
  - travis_retry python -m pip install tox
  # only download pandoc, the tests should work without a install of pypandoc
  - python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
  - export PATH=~/bin:$PATH
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov