language: python
python:
  - 3.6
  - 3.7
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

sudo: false

addons:
  apt_packages:
    - pandoc
    - texlive-xetex
install:
  - travis_retry python -m pip install tox
  - travis_retry python -m pip install pypandoc
  # only download pandoc, the tests should work without a install of pypandoc
  - python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
  - export PATH=~/bin:$PATH
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov